# Generated by Django 4.1 on 2024-03-21 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0002_posts_product_categories_rename_name_users_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('boost_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choapp.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choapp.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
