# Generated by Django 4.1 on 2024-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0005_users_email_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
