# Generated by Django 4.1 on 2024-03-25 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0009_remove_results_image_url_results_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='boost_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
