# Generated by Django 4.1 on 2024-03-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0010_alter_reactions_boost_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='choapp.posts'),
        ),
    ]
