# Generated by Django 5.0.4 on 2024-05-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0018_alter_results_result_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='jan_code',
            new_name='code',
        ),
    ]
