# Generated by Django 5.0.4 on 2024-05-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0019_rename_jan_code_products_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='code',
            new_name='jan_code',
        ),
    ]
