# Generated by Django 5.0.4 on 2024-05-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choapp', '0020_rename_code_products_jan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='asin_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='jan_code',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
